@ECHO OFF
ECHO Batch creating.png files
fsutil file createnew amure-logo.png 0
fsutil file createnew anses-logo.png 0
fsutil file createnew arn-logo.png 0
fsutil file createnew be-logo.png 0
fsutil file createnew biom-logo.png 0
fsutil file createnew c2ma-logo.png 0
fsutil file createnew c2p2-logo.png 0
fsutil file createnew cearc-logo.png 0
fsutil file createnew cedre-logo.png 0
fsutil file createnew cefe-logo.png 0
fsutil file createnew cefrem-logo.png 0
fsutil file createnew ecolab-logo.png 0
fsutil file createnew epoc-logo.png 0
fsutil file createnew genoscope-logo.png 0
fsutil file createnew geosciences-logo.png 0
fsutil file createnew gpm-logo.png 0
fsutil file createnew iate-logo.png 0
fsutil file createnew iccf-logo.png 0
fsutil file createnew icmpe-logo.png 0
fsutil file createnew imft-logo.png 0
fsutil file createnew imm-logo.png 0
fsutil file createnew imp-logo.png 0
fsutil file createnew imrcp-logo.png 0
fsutil file createnew inphyni-logo.png 0
fsutil file createnew iprem-logo.png 0
fsutil file createnew irdl-logo.png 0
fsutil file createnew l2c-logo.png 0
fsutil file createnew labocea-logo.png 0
fsutil file createnew lbcm-logo.png 0
fsutil file createnew lce-logo.png 0
fsutil file createnew lecob-logo.png 0
fsutil file createnew lee-logo.png 0
fsutil file createnew leesu-logo.png 0
fsutil file createnew legos-logo.png 0
fsutil file createnew lemar-logo.png 0
fsutil file createnew lerpac-logo.png 0
fsutil file createnew lgpmm-logo.png 0
fsutil file createnew ljp-logo.png 0
fsutil file createnew lmge-logo.png 0
fsutil file createnew lomic-logo.png 0
fsutil file createnew lops-logo.png 0
fsutil file createnew lov-logo.png 0
fsutil file createnew lubem-logo.png 0
fsutil file createnew mapiem-logo.png 0
fsutil file createnew marbec1-logo.png 0
fsutil file createnew marbec2-logo.png 0
fsutil file createnew mio-logo.png 0
fsutil file createnew mms-nantes-logo.png 0
fsutil file createnew mms-uco-logo.png 0
fsutil file createnew msc-logo.png 0
fsutil file createnew oreme-logo.png 0
fsutil file createnew promes-logo.png 0
fsutil file createnew rdt-logo.png 0
fsutil file createnew rmpf-logo.png 0
fsutil file createnew sayfood-logo.png 0
fsutil file createnew smpc-logo.png 0
fsutil file createnew takuvik-logo.png 0
fsutil file createnew uccs-logo.png 0

PAUSE